#!/bin/bash
#PBS -l select=1:ncpus=8
##PBS -l walltime=24:00:00
#PBS -m e
#PBS -j oe
#PBS -N qmqm-opt-rc
#PBS -q cf40
#PBS -P ACD111182

#module load orca/4.2
export PATH=$HOME/software/orca_5_0_2_linux_x86-64_shared_openmpi411:$HOME/software/openmpi/4.1.1/bin:$PATH
export LD_LIBRARY_PATH=$HOME/software/orca_5_0_2_linux_x86-64_shared_openmpi411:$HOME/software/openmpi/4.1.1/lib:$LD_LIBRARY_PATH

#export LD_LIBRARY_PATH=/home/nickyang69/software/orca_5_0_2_linux_x86-64_shared_openmpi411:/home/u4/nickyang69/software/openmpi/4.1.1/lib:$LD_LIBRARY_PATH
orca_full_path=$(which orca)

cd $PBS_O_WORKDIR
f=Mo-HIPT-NH3_0_2_bp86_lanl2dz_6-31gpol.opt.inp
$orca_full_path $f > ${f%.???}.out
