#!/bin/bash
#PBS -l select=1:ncpus=8
##PBS -l walltime=24:00:00
#PBS -m e
#PBS -j oe
#PBS -N qmqm-opt-int
#PBS -q cf40
#PBS -P ACD111182

#module load orca/4.2
export PATH=/home/nickyang69/software/orca_5_0_2_linux_x86-64_shared_openmpi411:/home/u4/nickyang69/software/openmpi/4.1.1/bin:$PATH
export LD_LIBRARY_PATH=/home/nickyang69/software/orca_5_0_2_linux_x86-64_shared_openmpi411:/home/u4/nickyang69/software/openmpi/4.1.1/lib:$LD_LIBRARY_PATH
orca_full_path=$(which orca)

cd $PBS_O_WORKDIR
f=tBu3C--Cl_0_1_bp86_xtb_6-31gpol_Int-SN1.scan.inp
$orca_full_path $f > ${f%.???}.out
